### ISSUE TITLE
Swagger 2.0 import support

### ISSUE THREAD

**Issue by htmldoug** [postmanlabs/postman-app-support#843]
Postman 1.0.3 claims support for importing Swagger files, but doesn't seem to support the latest swagger 2.0 spec [released](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#revision-history) on 2014-09-08.

The message should be changed to indicate that it supports Swagger **1.x** files, or support should be added for the current 2.0 spec.

Tested with the example file from editor.swagger.io (copied to [gist](https://gist.github.com/htmldoug/b9f907007ae4cad8c60b) here). 

![Postman 1.0.3 fails to import swagger 2.0 example file](https://cloud.githubusercontent.com/assets/663139/5372024/5e4891b0-8010-11e4-8e93-a147c4bf4cbe.png)

**Comment by brentonhouse** [comment]
Do you have a timetable for this?  Thanks!

**Comment by J4S0Nc** [comment]
Would like to see this feature added. Do you have an ETA?

**Comment by wdawson4** [comment]
:+1:  is anyone working on this? I'd be happy to contribute if help is needed.

**Comment by henkosch** [comment]
+1

**Comment by flavianh** [comment]
+1

**Comment by PiWhy** [comment]
+1

**Comment by abhijitkane** [comment]
@PiWhy @traxair @henkosch @wdawson4 @J4S0Nc @brentonhouse @kinlane 
Version 2.0.14 of Postman has basic support for the Swagger 2.0 format. Some aspects (like refs to remote schemas) are not supported, but the basic structure of any single schema should be import-able to a large extent.

**Comment by wdawson4** [comment]
@abhijitkane my swagger doc fails when i try to import it, but i have lots of refs. 

To clarify, The import should work if i just replace all of the refs with their properties ?

#### Example:

##### Won't import

``` yaml
paths:
  /tags
    patch:
      summary: Update a Tag.
      description: Update a `Tag` object given a name.
      parameters:
        - name: name
          in: path
          description: Tag name.
          required: true
          type: string
        - name: tag
          in: body
          description: Supplied Tag parameters to update.
          required: true
          schema:
             $ref: '#/definitions/Tag'
definitions:
  Tag:
    properties:
      _id:
         type: string
         description: Unique tag identifier.
      date:
        type: string
        description: Date the tag was created (ISO8601).
```

##### Importable Version?

``` yaml
paths:
  /tags
    patch:
      summary: Update a Tag.
      description: Update a `Tag` object given a name.
      parameters:
        - name: name
          in: path
          description: Tag name.
          required: true
          type: string
        - name: _id
          in: body
          type: string
          description: Unique tag identifier.
        - name: date
          in: body 
          type: string
          description: Date the tag was created (ISO8601).
```
